stages:
  - compile

.analysis_image: &image
  image: atlas/slc6-atlasos
  script:
    - echo $SERVICE_PASS | kinit $CERN_USER

compile_core:
  stage: compile
  <<: *image
  script:
    - echo $PWD
    - setupATLAS
    - lsetup git
    - lsetup "root 6.14.04-x86_64-slc6-gcc62-opt
    - lsetup cmake
    - mkdir build
    - cd build 
    - cmake ..
    - make
