stages:
  - compile
  
variables:
  GIT_STRATEGY: fetch
#  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /home/atlas/release_setup.sh
  - export MAKEFLAGS="-j`nproc` -l`nproc`"

.analysis_image: &image
  image: atlas/analysisbase:latest
  tags:
    - cvmfs
  script:
    - echo $SERVICE_PASS | kinit $CERN_USER

compile_core:
  stage: compile
  <<: *image
  script:
    - pwd
    - ls *
    - source /home/atlas/release_setup.sh
    - lsetup git
    - lsetup "root 6.14.04-x86_64-slc6-gcc62-opt
    - lsetup cmake
    - mkdir build
    - cd build 
    - cmake ..
    - make
