#!/bin/bash

WORKSPACEFILE=/tmp/exo/results/example_DS_04p000_combined_DS_04p000_model.root
WORKSPACENAME=combined
MODELCONFIGNAME=ModelConfig
DATASETNAME=obsData
PARAMNAME=mass
PARAMVALUE=123
WORKSPACETAG=test
OUTPUTFOLDER=validation
DOBLIND=1
CL=0.90

root -b -q runAsymptoticsCLs.C\(\"$WORKSPACEFILE\",\"$WORKSPACENAME\",\"$MODELCONFIGNAME\",\"$DATASETNAME\",\"$PARAMNAME\",$PARAMVALUE,\"$WORKSPACETAG\",\"$OUTPUTFOLDER\",$DOBLIND,$CL\)
